In [1]:
import pandas as pd
import numpy as np

data = {
    'order_id':[101,102,103,104,105,106,107,108,109,110],
    'customer':['A','B','C','A','B','C','A','B','C','A'],
    'city':['Delhi','Mumbai','Delhi','Pune','Mumbai','Delhi','Pune','Delhi','Mumbai','Pune'],
    'category':['Electronics','Clothing','Electronics','Furniture','Clothing','Furniture','Electronics','Clothing','Furniture','Electronics'],
    'sales':[200,500,150,800,700,300,400,600,900,100],
    'quantity':[2,5,1,4,3,2,3,5,4,1],
    'profit':[20,80,10,120,100,50,60,90,150,5]
}

df = pd.DataFrame(data)
print(df)

   order_id customer    city     category  sales  quantity  profit
0       101        A   Delhi  Electronics    200         2      20
1       102        B  Mumbai     Clothing    500         5      80
2       103        C   Delhi  Electronics    150         1      10
3       104        A    Pune    Furniture    800         4     120
4       105        B  Mumbai     Clothing    700         3     100
5       106        C   Delhi    Furniture    300         2      50
6       107        A    Pune  Electronics    400         3      60
7       108        B   Delhi     Clothing    600         5      90
8       109        C  Mumbai    Furniture    900         4     150
9       110        A    Pune  Electronics    100         1       5

## 2️⃣ SECTION 1 — Import / Export Data

In [3]:
#Q1- Load a CSV file named sales.csv into pandas.
#df = pd.read_csv('sales.csv')
#df.head()

In [4]:
df.head()

   order_id customer    city     category  sales  quantity  profit
0       101        A   Delhi  Electronics    200         2      20
1       102        B  Mumbai     Clothing    500         5      80
2       103        C   Delhi  Electronics    150         1      10
3       104        A    Pune    Furniture    800         4     120
4       105        B  Mumbai     Clothing    700         3     100

In [5]:
#Q2- Load an Excel file sales.xlsx
#df = pd.read_excel('sales.xlsx')
#df.head()

In [7]:
#Q4- Export the dataframe to a CSV file.
#df = pd.to_csv('sales.csv')
#print(df) #to_csv() is a DataFrame method, not pandas method.

In [ ]:
#pandas method
#df.to_csv('sales.csv', index = False)

In [6]:
#Q3- Load data from SQL database table orders
#df = pd.read_sql(query, connection_object)

In [ ]:
#OR--
#df = pd.read_sql('table_name', con = engine)

In [8]:
#Q5- Export the dataframe to Excel.
#df.to_excel('sales.csv')
#print(df)

In [9]:
#Q6- Convert dataframe to JSON file.
#df.to_json('sales.csv')
#print(df)

In [10]:
#Q7- Create a dataframe from dictionary.
#df = pd.DataFrame(data)
#print(df)

## 3️⃣ SECTION 2 — Inspect Data

In [11]:
#Q8- Show first 5 rows.
df.head()

   order_id customer    city     category  sales  quantity  profit
0       101        A   Delhi  Electronics    200         2      20
1       102        B  Mumbai     Clothing    500         5      80
2       103        C   Delhi  Electronics    150         1      10
3       104        A    Pune    Furniture    800         4     120
4       105        B  Mumbai     Clothing    700         3     100

In [12]:
#Q9- Show last 5 rows.
df.tail()

   order_id customer    city     category  sales  quantity  profit
5       106        C   Delhi    Furniture    300         2      50
6       107        A    Pune  Electronics    400         3      60
7       108        B   Delhi     Clothing    600         5      90
8       109        C  Mumbai    Furniture    900         4     150
9       110        A    Pune  Electronics    100         1       5

In [13]:
#Q10- Get random 3 rows.
df.sample(3)

   order_id customer   city     category  sales  quantity  profit
9       110        A   Pune  Electronics    100         1       5
7       108        B  Delhi     Clothing    600         5      90
5       106        C  Delhi    Furniture    300         2      50

In [14]:
#Q11- Check number of rows and columns.
df.shape

(10, 7)

In [3]:
#Q12- Get dataframe summary.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  10 non-null     int64
 1   customer  10 non-null     object
 2   city      10 non-null     object
 3   category  10 non-null     object
 4   sales     10 non-null     int64
 5   quantity  10 non-null     int64
 6   profit    10 non-null     int64
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [4]:
#Q13- Show column names.
df.columns

Index(['order_id', 'customer', 'city', 'category', 'sales', 'quantity',
       'profit'],
      dtype='object')

In [6]:
#Q14- Check data types of columns.
df.dtypes

order_id     int64
customer    object
city        object
category    object
sales        int64
quantity     int64
profit       int64
dtype: object

In [7]:
#Q15- Show statistical summary of dataset.
df.describe()

        order_id       sales   quantity      profit
count   10.00000   10.000000  10.000000   10.000000
mean   105.50000  465.000000   3.000000   68.500000
std      3.02765  280.921104   1.490712   48.422332
min    101.00000  100.000000   1.000000    5.000000
25%    103.25000  225.000000   2.000000   27.500000
50%    105.50000  450.000000   3.000000   70.000000
75%    107.75000  675.000000   4.000000   97.500000
max    110.00000  900.000000   5.000000  150.000000

In [8]:
#Q16- Show index of dataframe.
df.index

RangeIndex(start=0, stop=10, step=1)

## 4️⃣ SECTION 3 — Select / Index Data

In [9]:
#Q17-- Select only sales column
df['sales']

0    200
1    500
2    150
3    800
4    700
5    300
6    400
7    600
8    900
9    100
Name: sales, dtype: int64

In [12]:
#Q18- Select sales and profit columns
df[['sales', 'profit']]

   sales  profit
0    200      20
1    500      80
2    150      10
3    800     120
4    700     100
5    300      50
6    400      60
7    600      90
8    900     150
9    100       5

Important rule interviewers check:

Single column → single bracket
Multiple columns → double bracket

In [13]:
#Q19- Select first row using iloc
df.iloc[0]

order_id            101
customer              A
city              Delhi
category    Electronics
sales               200
quantity              2
profit               20
Name: 0, dtype: object

In [16]:
#20- Select row where index = 3 using loc
df.loc[3]

order_id          104
customer            A
city             Pune
category    Furniture
sales             800
quantity            4
profit            120
Name: 3, dtype: object

Key concept:

Method	Works with
iloc	position
loc	label/index

In [23]:
#21- Select value of row 2 column sales
df.loc[2, 'sales']

150

In [25]:
#Alternative using iloc:
df.iloc[2, 4]
#(because sales is the 5th column)

150

In [19]:
#22- Select rows from index 2 to 5
df.iloc[2:6]

   order_id customer    city     category  sales  quantity  profit
2       103        C   Delhi  Electronics    150         1      10
3       104        A    Pune    Furniture    800         4     120
4       105        B  Mumbai     Clothing    700         3     100
5       106        C   Delhi    Furniture    300         2      50

In [21]:
#23- Filter rows where sales > 500
df[df['sales'] > 500]

   order_id customer    city   category  sales  quantity  profit
3       104        A    Pune  Furniture    800         4     120
4       105        B  Mumbai   Clothing    700         3     100
7       108        B   Delhi   Clothing    600         5      90
8       109        C  Mumbai  Furniture    900         4     150

In [26]:
#OR--
df.query("sales > 500")

   order_id customer    city   category  sales  quantity  profit
3       104        A    Pune  Furniture    800         4     120
4       105        B  Mumbai   Clothing    700         3     100
7       108        B   Delhi   Clothing    600         5      90
8       109        C  Mumbai  Furniture    900         4     150

In [22]:
#24- Set order_id as index
df.set_index('order_id')

         customer    city     category  sales  quantity  profit
order_id
101             A   Delhi  Electronics    200         2      20
102             B  Mumbai     Clothing    500         5      80
103             C   Delhi  Electronics    150         1      10
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
106             C   Delhi    Furniture    300         2      50
107             A    Pune  Electronics    400         3      60
108             B   Delhi     Clothing    600         5      90
109             C  Mumbai    Furniture    900         4     150
110             A    Pune  Electronics    100         1       5

In [ ]:
#But this does NOT modify the dataframe permanently.
df.set_index('order_id', inplace = True)

In [27]:
#OR--
df = df.set_index('order_id')

⭐ Interview Trap (Very Common Question)

Interviewer may ask:

❓ Difference between:

df.loc[2]
df.iloc[2]

Answer:

Function	Meaning
loc	selects row using index label
iloc	selects row using position number

⭐ Another Interview Trick

❓ Difference between:

df['sales']
df[['sales']]

Answer:

df['sales'] → Series
df[['sales']] → DataFrame

Interviewers love this.

## 5️⃣ SECTION 4 — Sorting & Filtering

In [28]:
#25- Sort dataframe by sales ascending
df.sort_values('sales', ascending = True)

         customer    city     category  sales  quantity  profit
order_id
110             A    Pune  Electronics    100         1       5
103             C   Delhi  Electronics    150         1      10
101             A   Delhi  Electronics    200         2      20
106             C   Delhi    Furniture    300         2      50
107             A    Pune  Electronics    400         3      60
102             B  Mumbai     Clothing    500         5      80
108             B   Delhi     Clothing    600         5      90
105             B  Mumbai     Clothing    700         3     100
104             A    Pune    Furniture    800         4     120
109             C  Mumbai    Furniture    900         4     150

In [29]:
#26- Sort dataframe by sales descending
df.sort_values('sales', ascending = False)

         customer    city     category  sales  quantity  profit
order_id
109             C  Mumbai    Furniture    900         4     150
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
108             B   Delhi     Clothing    600         5      90
102             B  Mumbai     Clothing    500         5      80
107             A    Pune  Electronics    400         3      60
106             C   Delhi    Furniture    300         2      50
101             A   Delhi  Electronics    200         2      20
103             C   Delhi  Electronics    150         1      10
110             A    Pune  Electronics    100         1       5

In [40]:
#OR--
df.sort_values(by='sales', ascending=False)

         customer    city     category  sales  quantity  profit
order_id
109             C  Mumbai    Furniture    900         4     150
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
108             B   Delhi     Clothing    600         5      90
102             B  Mumbai     Clothing    500         5      80
107             A    Pune  Electronics    400         3      60
106             C   Delhi    Furniture    300         2      50
101             A   Delhi  Electronics    200         2      20
103             C   Delhi  Electronics    150         1      10
110             A    Pune  Electronics    100         1       5

In [41]:
#27-Sort by city and sales
df.sort_values(['city', 'sales'], ascending = [True,False])

         customer    city     category  sales  quantity  profit
order_id
108             B   Delhi     Clothing    600         5      90
106             C   Delhi    Furniture    300         2      50
101             A   Delhi  Electronics    200         2      20
103             C   Delhi  Electronics    150         1      10
109             C  Mumbai    Furniture    900         4     150
105             B  Mumbai     Clothing    700         3     100
102             B  Mumbai     Clothing    500         5      80
104             A    Pune    Furniture    800         4     120
107             A    Pune  Electronics    400         3      60
110             A    Pune  Electronics    100         1       5

In [31]:
#28- Filter rows where profit > 50
df[df['profit'] > 50]

         customer    city     category  sales  quantity  profit
order_id
102             B  Mumbai     Clothing    500         5      80
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
107             A    Pune  Electronics    400         3      60
108             B   Delhi     Clothing    600         5      90
109             C  Mumbai    Furniture    900         4     150

In [32]:
#29- Filter rows using query() where sales > 500
df.query("sales>500")

         customer    city   category  sales  quantity  profit
order_id
104             A    Pune  Furniture    800         4     120
105             B  Mumbai   Clothing    700         3     100
108             B   Delhi   Clothing    600         5      90
109             C  Mumbai  Furniture    900         4     150

In [33]:
#30- Select 3 random rows
df.sample(3)

         customer    city     category  sales  quantity  profit
order_id
109             C  Mumbai    Furniture    900         4     150
107             A    Pune  Electronics    400         3      60
103             C   Delhi  Electronics    150         1      10

In [42]:
#OR--
df.sample(n= 3)

         customer    city   category  sales  quantity  profit
order_id
104             A    Pune  Furniture    800         4     120
109             C  Mumbai  Furniture    900         4     150
102             B  Mumbai   Clothing    500         5      80

In [34]:
#31- Find top 3 highest sales
df.nlargest(3, 'sales')

         customer    city   category  sales  quantity  profit
order_id
109             C  Mumbai  Furniture    900         4     150
104             A    Pune  Furniture    800         4     120
105             B  Mumbai   Clothing    700         3     100

In [37]:
#32-Find 3 lowest profit
df.nsmallest(3, 'profit')

         customer   city     category  sales  quantity  profit
order_id
110             A   Pune  Electronics    100         1       5
103             C  Delhi  Electronics    150         1      10
101             A  Delhi  Electronics    200         2      20

In [39]:
#33- Filter columns containing word sales
df.filter(like = 'sales')

          sales
order_id
101         200
102         500
103         150
104         800
105         700
106         300
107         400
108         600
109         900
110         100

## 6️⃣ SECTION 5 — Cleaning Data

In [43]:
#34- Check for missing values.
df.isnull().sum()

customer    0
city        0
category    0
sales       0
quantity    0
profit      0
dtype: int64

In [59]:
#OR-
df.isna().sum()

customer    0
city        0
category    0
sales       0
quantity    0
profit      0
dtype: int64

In [44]:
#35- Drop rows with missing values.
df.dropna() #This does not modify the dataframe permanently.
#use--
#df.dropna(inplace = True)

         customer    city     category  sales  quantity  profit
order_id
101             A   Delhi  Electronics    200         2      20
102             B  Mumbai     Clothing    500         5      80
103             C   Delhi  Electronics    150         1      10
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
106             C   Delhi    Furniture    300         2      50
107             A    Pune  Electronics    400         3      60
108             B   Delhi     Clothing    600         5      90
109             C  Mumbai    Furniture    900         4     150
110             A    Pune  Electronics    100         1       5

In [46]:
#36- Fill missing sales with 0
df['sales'].fillna(0, inplace = True)

         customer    city     category  sales  quantity  profit
order_id
101             A   Delhi  Electronics    200         2      20
102             B  Mumbai     Clothing    500         5      80
103             C   Delhi  Electronics    150         1      10
104             A    Pune    Furniture    800         4     120
105             B  Mumbai     Clothing    700         3     100
106             C   Delhi    Furniture    300         2      50
107             A    Pune  Electronics    400         3      60
108             B   Delhi     Clothing    600         5      90
109             C  Mumbai    Furniture    900         4     150
110             A    Pune  Electronics    100         1       5

In [60]:
#37-Replace Delhi with DEL
df['city'].replace('Delhi', "DEL")
#Better (permanent change):
#df['city'].replace('Delhi', 'DEL', inplace= True)

order_id
101       DEL
102    Mumbai
103       DEL
104      Pune
105    Mumbai
106       DEL
107      Pune
108       DEL
109    Mumbai
110      Pune
Name: city, dtype: object

In [48]:
#38- Rename column sales → revenue
df.rename(columns = {'sales': 'revenue'})

         customer    city     category  revenue  quantity  profit
order_id
101             A   Delhi  Electronics      200         2      20
102             B  Mumbai     Clothing      500         5      80
103             C   Delhi  Electronics      150         1      10
104             A    Pune    Furniture      800         4     120
105             B  Mumbai     Clothing      700         3     100
106             C   Delhi    Furniture      300         2      50
107             A    Pune  Electronics      400         3      60
108             B   Delhi     Clothing      600         5      90
109             C  Mumbai    Furniture      900         4     150
110             A    Pune  Electronics      100         1       5

In [51]:
#39-Convert quantity column to float
df.dtypes['quantity']

dtype('int64')

In [55]:
df['quantity'] = pd.to_numeric(df['quantity'], errors= 'coerce').astype(float)

In [ ]:
#simple one
df['quantity']= df['quantity'].astype('float')

In [56]:
df.dtypes['quantity']

dtype('float64')

In [57]:
#40- Remove duplicate rows.
df.drop_duplicates()

         customer    city     category  sales  quantity  profit
order_id
101             A   Delhi  Electronics    200       2.0      20
102             B  Mumbai     Clothing    500       5.0      80
103             C   Delhi  Electronics    150       1.0      10
104             A    Pune    Furniture    800       4.0     120
105             B  Mumbai     Clothing    700       3.0     100
106             C   Delhi    Furniture    300       2.0      50
107             A    Pune  Electronics    400       3.0      60
108             B   Delhi     Clothing    600       5.0      90
109             C  Mumbai    Furniture    900       4.0     150
110             A    Pune  Electronics    100       1.0       5

In [58]:
#41- Reset dataframe index.
df.reset_index(drop = True, inplace = True)

   order_id customer    city     category  sales  quantity  profit
0       101        A   Delhi  Electronics    200       2.0      20
1       102        B  Mumbai     Clothing    500       5.0      80
2       103        C   Delhi  Electronics    150       1.0      10
3       104        A    Pune    Furniture    800       4.0     120
4       105        B  Mumbai     Clothing    700       3.0     100
5       106        C   Delhi    Furniture    300       2.0      50
6       107        A    Pune  Electronics    400       3.0      60
7       108        B   Delhi     Clothing    600       5.0      90
8       109        C  Mumbai    Furniture    900       4.0     150
9       110        A    Pune  Electronics    100       1.0       5

Explanation:

Parameter	Meaning
drop=True	remove old index
inplace=True	modify dataframe

## 7️⃣ SECTION 6 — GroupBy Operations

In [3]:
#42-Find total sales by city
total_sales_by_city = df.groupby('city')['sales'].sum().reset_index()
print(total_sales_by_city)

     city  sales
0   Delhi   1250
1  Mumbai   2100
2    Pune   1300

In [4]:
#43- Find average sales by category
avg_sales_by_category = df.groupby('category')['sales'].mean()
print(avg_sales_by_category)

category
Clothing       600.000000
Electronics    212.500000
Furniture      666.666667
Name: sales, dtype: float64

In [5]:
#44- Find total profit by city
total_profit_by_city = df.groupby('city')['profit'].sum()
print(total_profit_by_city)

city
Delhi     170
Mumbai    330
Pune      185
Name: profit, dtype: int64

In [6]:
#45- Count number of orders per customer
order_per_customer = df.groupby('customer')['order_id'].count()
print(order_per_customer)

customer
A    4
B    3
C    3
Name: order_id, dtype: int64

In [13]:
#OR-
df.groupby('customer').size()

customer
A    4
B    3
C    3
dtype: int64

In [7]:
#46- Find maximum sales per city
max_sales_per_city = df.groupby('city')['sales'].max()
print(max_sales_per_city)

city
Delhi     600
Mumbai    900
Pune      800
Name: sales, dtype: int64

In [14]:
#47- Create pivot table:
#city vs total sales
df.pivot_table(values= 'sales', index = 'city', aggfunc = 'sum')

        sales
city
Delhi    1250
Mumbai   2100
Pune     1300

Explanation:

Parameter	Meaning
values	column to aggregate
index	grouping column

In [10]:
#48- Aggregate:
#sales → mean
#profit → sum

df.agg({'sales': 'mean', 'profit': 'sum'})

sales     465.0
profit    685.0
dtype: float64

In [15]:
#OR-
#If the interviewer meant group by something, it would be:
df.groupby('city').agg({'sales': 'mean', 'profit': 'sum'})

             sales  profit
city
Delhi   312.500000     170
Mumbai  700.000000     330
Pune    433.333333     185

In [17]:
#49- Apply function to increase sales by 10.
#df.apply()

df['sales'] = df['sales'].apply(lambda x : x + 10)
print(df['sales'])

0    220
1    520
2    170
3    820
4    720
5    320
6    420
7    620
8    920
9    120
Name: sales, dtype: int64

In [12]:
#50- Transform quantity column by adding 5.
#df.transform()

df['quantity'] = df['quantity'] + 5
print(df['quantity'])

0     7
1    10
2     6
3     9
4     8
5     7
6     8
7    10
8     9
9     6
Name: quantity, dtype: int64

In [19]:
#OR-- Using Transform
df['quantity'] = df['quantity'].transform(lambda x:x+5)
print(df['quantity'])

0    12
1    15
2    11
3    14
4    13
5    12
6    13
7    15
8    14
9    11
Name: quantity, dtype: int64

⭐ Very Important Interview Concepts (From This Section)
1️⃣ Difference interviewers love to ask

groupby vs pivot_table

groupby	pivot_table
basic aggregation	spreadsheet-style summary
faster	more flexible

Example:

df.groupby('city')['sales'].sum()

vs

df.pivot_table(values='sales', index='city', aggfunc='sum')

In [20]:
#This gives mean sales for every row of that city.
df.groupby('city')['sales'].transform('mean')

0    332.500000
1    720.000000
2    332.500000
3    453.333333
4    720.000000
5    332.500000
6    453.333333
7    332.500000
8    720.000000
9    453.333333
Name: sales, dtype: float64

In [21]:
#Find total sales and average profit per city
df.groupby('city').agg({'sales' : 'sum', 'profit' : 'mean'})

        sales      profit
city
Delhi    1330   42.500000
Mumbai   2160  110.000000
Pune     1360   61.666667

## 8️⃣ SECTION 7 — Merge / Join

In [22]:
#Create another dataframe.

customers = pd.DataFrame({
    'customer' :  ['A', 'B', 'C'],
    'segment' : ['Premium', 'Standard', 'Premium']
})

df2 = customers
print(df2)

  customer   segment
0        A   Premium
1        B  Standard
2        C   Premium

In [23]:
#51- Concatenate two dataframes vertically.
pd.concat([df, df2])
#⚠️ Technically correct but logically mismatched

   order_id customer    city     category  sales  quantity  profit   segment
0     101.0        A   Delhi  Electronics  220.0      12.0    20.0       NaN
1     102.0        B  Mumbai     Clothing  520.0      15.0    80.0       NaN
2     103.0        C   Delhi  Electronics  170.0      11.0    10.0       NaN
3     104.0        A    Pune    Furniture  820.0      14.0   120.0       NaN
4     105.0        B  Mumbai     Clothing  720.0      13.0   100.0       NaN
5     106.0        C   Delhi    Furniture  320.0      12.0    50.0       NaN
6     107.0        A    Pune  Electronics  420.0      13.0    60.0       NaN
7     108.0        B   Delhi     Clothing  620.0      15.0    90.0       NaN
8     109.0        C  Mumbai    Furniture  920.0      14.0   150.0       NaN
9     110.0        A    Pune  Electronics  120.0      11.0     5.0       NaN
0       NaN        A     NaN          NaN    NaN       NaN     NaN   Premium
1       NaN        B     NaN          NaN    NaN       NaN     NaN  Standard
2       NaN        C     NaN          NaN    NaN       NaN     NaN   Premium

In [30]:
#Reason:
#df and df2 have different columns, so vertical concat will produce many NaN values.
pd.concat([df, df2], axis = 0)

   order_id customer    city     category  sales  quantity  profit   segment
0     101.0        A   Delhi  Electronics  220.0      12.0    20.0       NaN
1     102.0        B  Mumbai     Clothing  520.0      15.0    80.0       NaN
2     103.0        C   Delhi  Electronics  170.0      11.0    10.0       NaN
3     104.0        A    Pune    Furniture  820.0      14.0   120.0       NaN
4     105.0        B  Mumbai     Clothing  720.0      13.0   100.0       NaN
5     106.0        C   Delhi    Furniture  320.0      12.0    50.0       NaN
6     107.0        A    Pune  Electronics  420.0      13.0    60.0       NaN
7     108.0        B   Delhi     Clothing  620.0      15.0    90.0       NaN
8     109.0        C  Mumbai    Furniture  920.0      14.0   150.0       NaN
9     110.0        A    Pune  Electronics  120.0      11.0     5.0       NaN
0       NaN        A     NaN          NaN    NaN       NaN     NaN   Premium
1       NaN        B     NaN          NaN    NaN       NaN     NaN  Standard
2       NaN        C     NaN          NaN    NaN       NaN     NaN   Premium

In [24]:
#52- Concatenate horizontally.
pd.concat([df, df2], axis = 1)

,order_id,customer,city,category,sales,quantity,profit,customer,segment
0,101,A,Delhi,Electronics,220,12,20,A,Premium
1,102,B,Mumbai,Clothing,520,15,80,B,Standard
2,103,C,Delhi,Electronics,170,11,10,C,Premium
3,104,A,Pune,Furniture,820,14,120,NaN,NaN
4,105,B,Mumbai,Clothing,720,13,100,NaN,NaN
5,106,C,Delhi,Furniture,320,12,50,NaN,NaN
6,107,A,Pune,Electronics,420,13,60,NaN,NaN
7,108,B,Delhi,Clothing,620,15,90,NaN,NaN
8,109,C,Mumbai,Furniture,920,14,150,NaN,NaN
9,110,A,Pune,Electronics,120,11,5,NaN,NaN

Explanation:

axis	meaning
axis=0	vertical
axis=1	horizontal

In [25]:
#53- Merge df and customers using customer
df.merge(df2, on = 'customer')
#This performs an inner join by default.

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

In [31]:
#OR--
pd.merge(df, df2, on= 'customer')

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

In [32]:
#54- Perform inner join
pd.merge(df, df2, how = 'inner', on = 'customer')
#Inner join returns only matching rows.

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

In [33]:
#55- Perform outer join
pd.merge(df, df2, how = 'outer', on = 'customer')
#Outer join returns all rows from both tables.

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       104        A    Pune    Furniture    820        14     120   Premium
2       107        A    Pune  Electronics    420        13      60   Premium
3       110        A    Pune  Electronics    120        11       5   Premium
4       102        B  Mumbai     Clothing    520        15      80  Standard
5       105        B  Mumbai     Clothing    720        13     100  Standard
6       108        B   Delhi     Clothing    620        15      90  Standard
7       103        C   Delhi  Electronics    170        11      10   Premium
8       106        C   Delhi    Furniture    320        12      50   Premium
9       109        C  Mumbai    Furniture    920        14     150   Premium

In [34]:
#56- Perform left join
pd.merge(df, df2, how = 'left', on = 'customer')
#Left join keeps all rows from left dataframe (df).

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

In [35]:
#57- Perform right join
pd.merge(df, df2, how = 'right', on = 'customer')
#Right join keeps all rows from right dataframe (df2).

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       104        A    Pune    Furniture    820        14     120   Premium
2       107        A    Pune  Electronics    420        13      60   Premium
3       110        A    Pune  Electronics    120        11       5   Premium
4       102        B  Mumbai     Clothing    520        15      80  Standard
5       105        B  Mumbai     Clothing    720        13     100  Standard
6       108        B   Delhi     Clothing    620        15      90  Standard
7       103        C   Delhi  Electronics    170        11      10   Premium
8       106        C   Delhi    Furniture    320        12      50   Premium
9       109        C  Mumbai    Furniture    920        14     150   Premium

In [36]:
#Find sales and customer segment together.
df.merge(customers, on = 'customer', how = 'left')

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

In [37]:
#3️⃣ Join using different column names
pd.merge(df, df2, left_on = 'customer', right_on = 'customer')

   order_id customer    city     category  sales  quantity  profit   segment
0       101        A   Delhi  Electronics    220        12      20   Premium
1       102        B  Mumbai     Clothing    520        15      80  Standard
2       103        C   Delhi  Electronics    170        11      10   Premium
3       104        A    Pune    Furniture    820        14     120   Premium
4       105        B  Mumbai     Clothing    720        13     100  Standard
5       106        C   Delhi    Furniture    320        12      50   Premium
6       107        A    Pune  Electronics    420        13      60   Premium
7       108        B   Delhi     Clothing    620        15      90  Standard
8       109        C  Mumbai    Furniture    920        14     150   Premium
9       110        A    Pune  Electronics    120        11       5   Premium

## 9️⃣ SECTION 8 — Statistical Operations

In [53]:
#58- Find mean sales.
df['sales'] = df['sales'].mean()
print(df['sales'])
#This replaces the entire sales column with the mean value.

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
Name: sales, dtype: float64

In [54]:
df['sales'].mean()

0.0

In [55]:
#-- OR--
mean_sales = df['sales'].mean()
print(mean_sales)

0.0

In [ ]:
#If we have two dataframes (df and df2)
#df['sales'].mean()
#df2['sales'].mean()

In [56]:
#If you want combined mean:
pd.concat([df, df2])['sales'].mean()

0.0

In [57]:
#59- Find median profit.
df['profit'] = df['profit'].median()
print(df['profit'])
#This replaces the entire sales column with the median value.

0    70.0
1    70.0
2    70.0
3    70.0
4    70.0
5    70.0
6    70.0
7    70.0
8    70.0
9    70.0
Name: profit, dtype: float64

In [58]:
#OR --
median_profit = df['profit'].median()
print(median_profit)

70.0

In [59]:
#60- Find standard deviation of sales.
std_sales = df['sales'].std()
print(std_sales)

0.0

In [60]:
#61- Find variance of quantity.
var_quantity = df['quantity'].var()
print(var_quantity)

2.1912802922805884e-31

In [61]:
#62- Find total sales.
total_sales = df['sales'].sum()
print(total_sales)

0.0

In [62]:
#63- Find minimum sales.
min_sales = df['sales'].min()
print(min_sales)

0.0

In [63]:
#64- Find maximum profit.
max_profit = df['profit'].max()
print(max_profit)

70.0

In [50]:
#65- Count non-null values.
df.count()

order_id    10
customer    10
city        10
category    10
sales       10
quantity    10
profit      10
dtype: int64

In [68]:
#66- Find correlation matrix.
df.select_dtypes(include = 'number').corr()

          order_id  sales  quantity  profit
order_id       1.0    NaN       NaN     NaN
sales          NaN    NaN       NaN     NaN
quantity       NaN    NaN       NaN     NaN
profit         NaN    NaN       NaN     NaN

Important Interview Concept

Correlation formula

r = \frac{\sum (x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum (x_i-\bar{x})^2}\sqrt{\sum (y_i-\bar{y})^2}}

This measures the linear relationship between two variables.

Values range from:

Value	Meaning
+1	strong positive relationship
0	no relationship
-1	strong negative relationship

⭐ The Key Concept You Missed

When calculating statistics, never assign back to the column.

Wrong pattern you used:

df['sales'] = df['sales'].mean()

Correct pattern:

df['sales'].mean()

or

mean_sales = df['sales'].mean()

In [65]:
#⭐ Very Common Interview Question
#Find all statistics together

df['sales'].describe()

count    10.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
Name: sales, dtype: float64

In [67]:
#⭐ Another Real Interview Question
#Find correlation between sales and profit
df[['sales', 'profit']].corr()

        sales  profit
sales     NaN     NaN
profit    NaN     NaN

## ⭐ REAL INTERVIEW QUESTIONS (Important)

In [71]:
#67- Find top 3 cities with highest sales
top_3_cities = df['sales'].nlargest().head(3)
print(top_3_cities)
#This finds top 3 rows by sales, not cities with highest total sales.
#wrong answer

0    0.0
1    0.0
2    0.0
Name: sales, dtype: float64

In [84]:
#corrct answer
df.groupby('city')['sales'].nlargest().head(3)

city
Delhi  0    0.0
       2    0.0
       5    0.0
Name: sales, dtype: float64

In [87]:
#68- Find customer with highest total purchase
highest_total_purchase = df.groupby('customer')['sales'].sum().idxmax()
print(highest_total_purchase)

A

In [72]:
#69- Find category with highest profit
category_with_highest_profit = df.groupby('category')['profit'].max()
print(category_with_highest_profit)

category
Clothing       70.0
Electronics    70.0
Furniture      70.0
Name: profit, dtype: float64

In [88]:
#OR--
category_with_highest_profit = df.groupby('customer')['sales'].sum().sort_values(ascending = False).head(1)
print(category_with_highest_profit)

customer
A    0.0
Name: sales, dtype: float64

In [73]:
#70- Find average sales per customer
avg_sales_per_cust = df.groupby('customer')['sales'].mean()
print(avg_sales_per_cust)
#❌ Not exactly correct
#This gives max profit per category, not category with highest total profit.

customer
A    0.0
B    0.0
C    0.0
Name: sales, dtype: float64

In [90]:
df.groupby('category')['profit'].sum().idxmax()

'Electronics'

In [76]:
#71- Find total quantity sold per city
total_quantity_sold = df.groupby('city')['quantity'].sum()
print(total_quantity_sold)

city
Delhi     8.888889
Mumbai    6.666667
Pune      6.666667
Name: quantity, dtype: float64

In [77]:
#72- Find city with lowest profit
city_with_lowest = df.groupby('city')['profit'].min()
print(city_with_lowest)
#❌ Incorrect logic

#This gives minimum profit per city, not city with lowest total profit.

city
Delhi     70.0
Mumbai    70.0
Pune      70.0
Name: profit, dtype: float64

In [91]:
#Coorect answer
df.groupby('city')['profit'].sum().idxmin()

'Mumbai'

## ⭐ Sigma Analytics Level Questions

In [92]:
#73- Find top 2 cities by total sales
top_2_cities = df.groupby('city')['sales'].sum().nlargest(2)
print(top_2_cities)

city
Delhi     0.0
Mumbai    0.0
Name: sales, dtype: float64

In [93]:
#OR --
df.groupby('city')['sales'].sum().sort_values(ascending = False).head(2)

city
Delhi     0.0
Mumbai    0.0
Name: sales, dtype: float64

In [81]:
#74- Find profit percentage
#profit / sales * 100
profit_percentage = (df['profit']/df['sales']) * 100
print(profit_percentage)

0    inf
1    inf
2    inf
3    inf
4    inf
5    inf
6    inf
7    inf
8    inf
9    inf
dtype: float64

In [94]:
#You could also create a column:

df['profit_pct'] = (df['profit']/df['sales']) * 100

In [82]:
#75- Create new column revenue_per_unit
#sales / quantity
df['revenue_per_unit'] = df['sales']/df['quantity']
print(df['revenue_per_unit'])

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
Name: revenue_per_unit, dtype: float64

In [95]:
#76- Find city where average profit > 80
avg_profit = df.groupby('city')['profit'].mean()
print(avg_profit > 80)

city
Delhi     False
Mumbai    False
Pune      False
Name: profit, dtype: bool

In [96]:
#OR--
df.groupby('city')['profit'].mean()[lambda x:x > 80]

Series([], Name: profit, dtype: float64)

⭐ Most Important Concept You Missed

When interviewers ask:

highest / lowest city / customer / category

You usually need 3 steps:

df.groupby('column')['metric'].sum().sort_values()

Example pattern:

df.groupby('city')['sales'].sum().nlargest(3)

This pattern solves many interview questions.

⭐ Example Interview Pattern

Top N entities

df.groupby('city')['sales'].sum().nlargest(3)

Lowest entity

df.groupby('city')['profit'].sum().idxmin()

Best customer

df.groupby('customer')['sales'].sum().idxmax()
⭐ Your Overall Pandas EDA Level

You are currently around:

70–75% interview readiness

Which is actually good.

To reach 90% level, you mainly need practice in:

• GroupBy + aggregation logic
• Top N / Lowest N problems
• idxmax / idxmin usage