# 🟢 EDA Practice

## 🟢 Step 1: Create This DataFrame

In [134]:
import pandas as pd
import numpy as np

data = {
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'customer_name': ['Amit', 'Neha', 'Raj', 'Amit', 'Kiran', 'Neha', None, 'Riya', 'Sahil', 'Riya'],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi', 'Chennai', None, 'Delhi', 'Mumbai'],
    'sales': [5000, 7000, 4000, None, 6500, 7000, 3000, 8000, None, 7500],
    'quantity': [5, 7, 4, 6, None, 7, 3, 8, 2, 7],
    'order_date': pd.to_datetime([
        '2024-01-01', '2024-01-05', '2024-01-07', '2024-01-10',
        '2024-01-15', '2024-01-20', '2024-01-25', '2024-01-28',
        '2024-02-01', '2024-02-05'
    ])
}

df = pd.DataFrame(data)
print(df)

   order_id customer_name     city   sales  quantity order_date
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05
2       103           Raj    Delhi  4000.0       4.0 2024-01-07
3       104          Amit  Chennai     NaN       6.0 2024-01-10
4       105         Kiran   Mumbai  6500.0       NaN 2024-01-15
5       106          Neha    Delhi  7000.0       7.0 2024-01-20
6       107          None  Chennai  3000.0       3.0 2024-01-25
7       108          Riya     None  8000.0       8.0 2024-01-28
8       109         Sahil    Delhi     NaN       2.0 2024-02-01
9       110          Riya   Mumbai  7500.0       7.0 2024-02-05

## 1️⃣ Inspect Data (Basic Interview Warmup)

### 1- Display first 5 rows.

In [3]:
df.head(5)

   order_id customer_name     city   sales  quantity order_date
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05
2       103           Raj    Delhi  4000.0       4.0 2024-01-07
3       104          Amit  Chennai     NaN       6.0 2024-01-10
4       105         Kiran   Mumbai  6500.0       NaN 2024-01-15

### 2- Display last 3 rows.

In [4]:
df.tail(3)

   order_id customer_name    city   sales  quantity order_date
7       108          Riya    None  8000.0       8.0 2024-01-28
8       109         Sahil   Delhi     NaN       2.0 2024-02-01
9       110          Riya  Mumbai  7500.0       7.0 2024-02-05

### 3- Show random 4 rows.

In [9]:
df.sample(4)

   order_id customer_name     city   sales  quantity order_date
5       106          Neha    Delhi  7000.0       7.0 2024-01-20
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
3       104          Amit  Chennai     NaN       6.0 2024-01-10
7       108          Riya     None  8000.0       8.0 2024-01-28

### 4- Find total number of rows and columns.

In [10]:
df.shape

(10, 6)

### 5- Check data types of all columns.

In [15]:
df.dtypes

order_id                  int64
customer_name            object
city                     object
sales                   float64
quantity                float64
order_date       datetime64[ns]
dtype: object

### 6- Get summary info of dataset.

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10 non-null     int64
 1   customer_name  9 non-null      object
 2   city           9 non-null      object
 3   sales          8 non-null      float64
 4   quantity       9 non-null      float64
 5   order_date     10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 612.0+ bytes

### 7- Get statistical summary of numeric columns.

In [16]:
df.describe()

        order_id        sales  quantity           order_date
count   10.00000     8.000000  9.000000                   10
mean   105.50000  6000.000000  5.444444  2024-01-17 21:36:00
min    101.00000  3000.000000  2.000000  2024-01-01 00:00:00
25%    103.25000  4750.000000  4.000000  2024-01-07 18:00:00
50%    105.50000  6750.000000  6.000000  2024-01-17 12:00:00
75%    107.75000  7125.000000  7.000000  2024-01-27 06:00:00
max    110.00000  8000.000000  8.000000  2024-02-05 00:00:00
std      3.02765  1792.842914  2.068279                  NaN

### 8- Print only column names.

In [19]:
df.columns

Index(['order_id', 'customer_name', 'city', 'sales', 'quantity', 'order_date'], dtype='object')

### 9- Display index range.

In [20]:
df.index

RangeIndex(start=0, stop=10, step=1)

## 🔹 2️⃣ Import / Export (Conceptual + Practical)

### 10- How would you read this dataset from a CSV file?

In [21]:
#df= pd.read_csv('file_path.csv')
#df.head()

### 11- Write code to export this DataFrame to Excel.

In [22]:
#df.to_excel(filename.xlsx', index=False)

### 12- How would you load data from SQL table into Pandas?

In [43]:
#df.to_sql('table_name', connection_object, if_exists = 'replace')

### 13- How would you convert this DataFrame into JSON?

In [44]:
#df.to_json('filename.json')

### 14- Create a new DataFrame manually using dictionary with 3 rows.

In [26]:
new_df = {
    'student_name' : ['Anu', 'Anushree', 'Raj'],
    'Class' : ['First', 'Second', 'Third'],
    'Hobbies' : ['Coocking', 'Playing', 'Dancing']
}
df1 = pd.DataFrame(new_df)
print(df1)

  student_name   Class   Hobbies
0          Anu   First  Coocking
1     Anushree  Second   Playing
2          Raj   Third   Dancing

## 🔹 3️⃣ Select & Index

### 15- Select only 'customer_name' column.

In [28]:
df['customer_name']

0     Amit
1     Neha
2      Raj
3     Amit
4    Kiran
5     Neha
6     None
7     Riya
8    Sahil
9     Riya
Name: customer_name, dtype: object

### 16- Select 'city' and 'sales'.

In [33]:
df[['city' , 'sales']]

      city   sales
0    Delhi  5000.0
1   Mumbai  7000.0
2    Delhi  4000.0
3  Chennai     NaN
4   Mumbai  6500.0
5    Delhi  7000.0
6  Chennai  3000.0
7     None  8000.0
8    Delhi     NaN
9   Mumbai  7500.0

### 17- Select first row using iloc.

In [45]:
df.iloc[0:1]
#df.iloc[0]

   order_id customer_name   city   sales  quantity order_date
0       101          Amit  Delhi  5000.0       5.0 2024-01-01

### 18- Select first row using loc.

In [35]:
df.loc[0]

order_id                         101
customer_name                   Amit
city                           Delhi
sales                         5000.0
quantity                         5.0
order_date       2024-01-01 00:00:00
Name: 0, dtype: object

### 19- Select value of sales for order_id 105.

In [47]:
df.loc[df['order_id'] == 105, 'sales']
#df[df['order_id'] == 105]['sales']

4    6500.0
Name: sales, dtype: float64

### 20- Filter rows where sales > 6000.

In [37]:
df[df['sales'] > 6000]

   order_id customer_name    city   sales  quantity order_date
1       102          Neha  Mumbai  7000.0       7.0 2024-01-05
4       105         Kiran  Mumbai  6500.0       NaN 2024-01-15
5       106          Neha   Delhi  7000.0       7.0 2024-01-20
7       108          Riya    None  8000.0       8.0 2024-01-28
9       110          Riya  Mumbai  7500.0       7.0 2024-02-05

### 21- Slice first 5 rows and first 3 columns.

In [38]:
df.iloc[:5, 0:3]

   order_id customer_name     city
0       101          Amit    Delhi
1       102          Neha   Mumbai
2       103           Raj    Delhi
3       104          Amit  Chennai
4       105         Kiran   Mumbai

### 22- Set 'order_id' as index.

In [40]:
df.set_index('order_id')

         customer_name     city   sales  quantity order_date
order_id
101               Amit    Delhi  5000.0       5.0 2024-01-01
102               Neha   Mumbai  7000.0       7.0 2024-01-05
103                Raj    Delhi  4000.0       4.0 2024-01-07
104               Amit  Chennai     NaN       6.0 2024-01-10
105              Kiran   Mumbai  6500.0       NaN 2024-01-15
106               Neha    Delhi  7000.0       7.0 2024-01-20
107               None  Chennai  3000.0       3.0 2024-01-25
108               Riya     None  8000.0       8.0 2024-01-28
109              Sahil    Delhi     NaN       2.0 2024-02-01
110               Riya   Mumbai  7500.0       7.0 2024-02-05

## 🔹 4️⃣ Cleaning Data (VERY IMPORTANT FOR INTERVIEW)

### 23- Count total null values in each column.

In [48]:
df.isna().sum()

order_id         0
customer_name    1
city             1
sales            2
quantity         1
order_date       0
dtype: int64

In [49]:
df.isnull().sum()

order_id         0
customer_name    1
city             1
sales            2
quantity         1
order_date       0
dtype: int64

### 24- Drop rows with any null values.

In [51]:
df.drop_duplicates()

   order_id customer_name     city   sales  quantity order_date
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05
2       103           Raj    Delhi  4000.0       4.0 2024-01-07
3       104          Amit  Chennai     NaN       6.0 2024-01-10
4       105         Kiran   Mumbai  6500.0       NaN 2024-01-15
5       106          Neha    Delhi  7000.0       7.0 2024-01-20
6       107          None  Chennai  3000.0       3.0 2024-01-25
7       108          Riya     None  8000.0       8.0 2024-01-28
8       109         Sahil    Delhi     NaN       2.0 2024-02-01
9       110          Riya   Mumbai  7500.0       7.0 2024-02-05

In [151]:
df.dropna()

   order_id customer_name    city   sales  quantity order_date
0       101          Amit   Delhi  5000.0       5.0 2024-01-01
1       102          Neha  Mumbai  7000.0       7.0 2024-01-05
2       103           Raj   Delhi  4000.0       4.0 2024-01-07
5       106          Neha   Delhi  7000.0       7.0 2024-01-20
9       110          Riya  Mumbai  7500.0       7.0 2024-02-05

### 25- Replace null sales with mean sales.

In [53]:
df['sales'] = df['sales'].fillna(df['sales'].mean())
df['sales']

0    5000.0
1    7000.0
2    4000.0
3    6000.0
4    6500.0
5    7000.0
6    3000.0
7    8000.0
8    6000.0
9    7500.0
Name: sales, dtype: float64

### 26- Replace null quantity with 0.

In [54]:
df.fillna(0)

   order_id customer_name     city   sales  quantity order_date
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05
2       103           Raj    Delhi  4000.0       4.0 2024-01-07
3       104          Amit  Chennai  6000.0       6.0 2024-01-10
4       105         Kiran   Mumbai  6500.0       0.0 2024-01-15
5       106          Neha    Delhi  7000.0       7.0 2024-01-20
6       107             0  Chennai  3000.0       3.0 2024-01-25
7       108          Riya        0  8000.0       8.0 2024-01-28
8       109         Sahil    Delhi  6000.0       2.0 2024-02-01
9       110          Riya   Mumbai  7500.0       7.0 2024-02-05

### 27- Remove duplicate customer_name rows.

In [55]:
df.drop_duplicates(['customer_name'])

   order_id customer_name     city   sales  quantity order_date
0       101          Amit    Delhi  5000.0       5.0 2024-01-01
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05
2       103           Raj    Delhi  4000.0       4.0 2024-01-07
4       105         Kiran   Mumbai  6500.0       NaN 2024-01-15
6       107          None  Chennai  3000.0       3.0 2024-01-25
7       108          Riya     None  8000.0       8.0 2024-01-28
8       109         Sahil    Delhi  6000.0       2.0 2024-02-01

### 28- Rename column 'sales' to 'total_sales'.

In [56]:
df.rename(columns = {'sales': 'total_sales'})

   order_id customer_name     city  total_sales  quantity order_date
0       101          Amit    Delhi       5000.0       5.0 2024-01-01
1       102          Neha   Mumbai       7000.0       7.0 2024-01-05
2       103           Raj    Delhi       4000.0       4.0 2024-01-07
3       104          Amit  Chennai       6000.0       6.0 2024-01-10
4       105         Kiran   Mumbai       6500.0       NaN 2024-01-15
5       106          Neha    Delhi       7000.0       7.0 2024-01-20
6       107          None  Chennai       3000.0       3.0 2024-01-25
7       108          Riya     None       8000.0       8.0 2024-01-28
8       109         Sahil    Delhi       6000.0       2.0 2024-02-01
9       110          Riya   Mumbai       7500.0       7.0 2024-02-05

### 29- Convert quantity column to int.

In [61]:
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce').astype('Int64')
df['quantity']

0       5
1       7
2       4
3       6
4    <NA>
5       7
6       3
7       8
8       2
9       7
Name: quantity, dtype: Int64

In [62]:
df['quantity'].dtypes

Int64Dtype()

### 30- Reset index after dropping rows.

In [63]:
df.reset_index()

   index  order_id customer_name     city   sales  quantity order_date
0      0       101          Amit    Delhi  5000.0         5 2024-01-01
1      1       102          Neha   Mumbai  7000.0         7 2024-01-05
2      2       103           Raj    Delhi  4000.0         4 2024-01-07
3      3       104          Amit  Chennai  6000.0         6 2024-01-10
4      4       105         Kiran   Mumbai  6500.0      <NA> 2024-01-15
5      5       106          Neha    Delhi  7000.0         7 2024-01-20
6      6       107          None  Chennai  3000.0         3 2024-01-25
7      7       108          Riya     None  8000.0         8 2024-01-28
8      8       109         Sahil    Delhi  6000.0         2 2024-02-01
9      9       110          Riya   Mumbai  7500.0         7 2024-02-05

## 🔹 5️⃣ Sorting & Filtering

### 31- Sort dataset by sales ascending.

In [65]:
df['sales'].sort_values(ascending = True)

6    3000.0
2    4000.0
0    5000.0
3    6000.0
8    6000.0
4    6500.0
1    7000.0
5    7000.0
9    7500.0
7    8000.0
Name: sales, dtype: float64

### 32- Sort by city ascending and sales descending.

In [67]:
df.sort_values(['city', 'sales'], ascending = [True, False])

   order_id customer_name     city   sales  quantity order_date
3       104          Amit  Chennai  6000.0         6 2024-01-10
6       107          None  Chennai  3000.0         3 2024-01-25
5       106          Neha    Delhi  7000.0         7 2024-01-20
8       109         Sahil    Delhi  6000.0         2 2024-02-01
0       101          Amit    Delhi  5000.0         5 2024-01-01
2       103           Raj    Delhi  4000.0         4 2024-01-07
9       110          Riya   Mumbai  7500.0         7 2024-02-05
1       102          Neha   Mumbai  7000.0         7 2024-01-05
4       105         Kiran   Mumbai  6500.0      <NA> 2024-01-15
7       108          Riya     None  8000.0         8 2024-01-28

### 33- Get top 3 highest sales.

In [68]:
top_3_highest_sales = df.nlargest(3, 'sales')
top_3_highest_sales

   order_id customer_name    city   sales  quantity order_date
7       108          Riya    None  8000.0         8 2024-01-28
9       110          Riya  Mumbai  7500.0         7 2024-02-05
1       102          Neha  Mumbai  7000.0         7 2024-01-05

### 34- Get bottom 2 sales.

In [69]:
bottom_2_sales = df.nsmallest(2, 'sales')
bottom_2_sales

   order_id customer_name     city   sales  quantity order_date
6       107          None  Chennai  3000.0         3 2024-01-25
2       103           Raj    Delhi  4000.0         4 2024-01-07

### 35- Filter customers from Delhi.

In [71]:
cust_from_delhi = df[df['city'] == 'Delhi']
cust_from_delhi

   order_id customer_name   city   sales  quantity order_date
0       101          Amit  Delhi  5000.0         5 2024-01-01
2       103           Raj  Delhi  4000.0         4 2024-01-07
5       106          Neha  Delhi  7000.0         7 2024-01-20
8       109         Sahil  Delhi  6000.0         2 2024-02-01

In [73]:
#using .loc
cust_from_delhi = df.loc[df['city'] == 'Delhi']
cust_from_delhi

   order_id customer_name   city   sales  quantity order_date
0       101          Amit  Delhi  5000.0         5 2024-01-01
2       103           Raj  Delhi  4000.0         4 2024-01-07
5       106          Neha  Delhi  7000.0         7 2024-01-20
8       109         Sahil  Delhi  6000.0         2 2024-02-01

In [74]:
#Case-Insensitive Version
cust_from_delhi = df[df['city'].str.lower() == 'delhi']
cust_from_delhi

   order_id customer_name   city   sales  quantity order_date
0       101          Amit  Delhi  5000.0         5 2024-01-01
2       103           Raj  Delhi  4000.0         4 2024-01-07
5       106          Neha  Delhi  7000.0         7 2024-01-20
8       109         Sahil  Delhi  6000.0         2 2024-02-01

### 36- Use query() to filter sales greater than 6000.

In [76]:
df[df['sales'] > 6000]

   order_id customer_name    city   sales  quantity order_date
1       102          Neha  Mumbai  7000.0         7 2024-01-05
4       105         Kiran  Mumbai  6500.0      <NA> 2024-01-15
5       106          Neha   Delhi  7000.0         7 2024-01-20
7       108          Riya    None  8000.0         8 2024-01-28
9       110          Riya  Mumbai  7500.0         7 2024-02-05

In [78]:
#use query()
df.query('sales > 6000')['sales']

1    7000.0
4    6500.0
5    7000.0
7    8000.0
9    7500.0
Name: sales, dtype: float64

In [79]:
df.query('sales > 6000')

   order_id customer_name    city   sales  quantity order_date
1       102          Neha  Mumbai  7000.0         7 2024-01-05
4       105         Kiran  Mumbai  6500.0      <NA> 2024-01-15
5       106          Neha   Delhi  7000.0         7 2024-01-20
7       108          Riya    None  8000.0         8 2024-01-28
9       110          Riya  Mumbai  7500.0         7 2024-02-05

### 37- Select random 3 rows.

In [80]:
df.sample(3)

   order_id customer_name     city   sales  quantity order_date
9       110          Riya   Mumbai  7500.0         7 2024-02-05
3       104          Amit  Chennai  6000.0         6 2024-01-10
7       108          Riya     None  8000.0         8 2024-01-28

### 38- Filter columns that contain word "sale".

In [82]:
df['sales']

0    5000.0
1    7000.0
2    4000.0
3    6000.0
4    6500.0
5    7000.0
6    3000.0
7    8000.0
8    6000.0
9    7500.0
Name: sales, dtype: float64

In [86]:
df.filter(like = 'sales')

    sales
0  5000.0
1  7000.0
2  4000.0
3  6000.0
4  6500.0
5  7000.0
6  3000.0
7  8000.0
8  6000.0
9  7500.0

In [89]:
#using loc
df.loc[:, df.columns.str.contains('sales', case = False)]
#case = False for case sensitive

    sales
0  5000.0
1  7000.0
2  4000.0
3  6000.0
4  6500.0
5  7000.0
6  3000.0
7  8000.0
8  6000.0
9  7500.0

## 🔹 6️⃣ GroupBy (Most Asked in DA Interviews)

### 39- Find total sales by city.

In [91]:
df.groupby('city')['sales'].sum().reset_index()

      city    sales
0  Chennai   9000.0
1    Delhi  22000.0
2   Mumbai  21000.0

### 40- Find average sales by customer_name.

In [92]:
df.groupby('customer_name')['sales'].mean().reset_index()

  customer_name   sales
0          Amit  5500.0
1         Kiran  6500.0
2          Neha  7000.0
3           Raj  4000.0
4          Riya  7750.0
5         Sahil  6000.0

### 41- Count number of orders per city.

In [93]:
df.groupby('city')['order_id'].count().reset_index()

      city  order_id
0  Chennai         2
1    Delhi         4
2   Mumbai         3

### 42- Find max sales per city.

In [94]:
df.groupby('city')['sales'].max().reset_index()

      city   sales
0  Chennai  6000.0
1    Delhi  7000.0
2   Mumbai  7500.0

### 43- Aggregate total sales and average quantity per city.

In [95]:
df.groupby('city').agg({'sales': 'sum', 'quantity' : 'mean' })

           sales  quantity
city
Chennai   9000.0       4.5
Delhi    22000.0       4.5
Mumbai   21000.0       7.0

### 44- Create pivot table of city vs total sales.

In [99]:
pd.pivot_table(df, index='city', values='sales', aggfunc='sum')

           sales
city
Chennai   9000.0
Delhi    22000.0
Mumbai   21000.0

## 🔹 7️⃣ Statistical Operations

### 45- Find mean of sales.

In [104]:
df['sales'].mean()

6000.0

### 46- Find median of quantity.

In [105]:
df['quantity'].median()

6.0

### 47- Find standard deviation of sales.

In [106]:
df['sales'].std()

1581.1388300841897

### 48- Find total sales.

In [107]:
df['sales'].sum()

60000.0

### 49- Find minimum sales.

In [108]:
df['sales'].min()

3000.0

### 50- Find correlation between sales and quantity.

In [110]:
df[['sales', 'quantity']].corr()

             sales  quantity
sales     1.000000  0.769561
quantity  0.769561  1.000000

In [111]:
# OR
df['sales'].corr(df['quantity'])

0.7695609306442384

## 🔹 8️⃣ Merge & Join (Advanced Level)

### Now create second DataFrame:

In [116]:
customer_info = {
    'customer_name': ['Amit', 'Neha', 'Raj', 'Kiran', 'Riya'],
    'age': [30, 25, 35, 28, 22],
    'membership': ['Gold', 'Silver', 'Gold', 'Silver', 'Platinum']
}

df2 = pd.DataFrame(customer_info)
df2

  customer_name  age membership
0          Amit   30       Gold
1          Neha   25     Silver
2           Raj   35       Gold
3         Kiran   28     Silver
4          Riya   22   Platinum

### 51- Merge df and df2 on customer_name (inner join).

In [126]:
merged_df2 = pd.merge(df, df2, how = 'inner', on = 'customer_name')
merged_df2

,order_id,customer_name,city,sales,quantity,order_date,age,membership
0,101,Amit,Delhi,5000.0,5,2024-01-01,30,Gold
1,102,Neha,Mumbai,7000.0,7,2024-01-05,25,Silver
2,103,Raj,Delhi,4000.0,4,2024-01-07,35,Gold
3,104,Amit,Chennai,6000.0,6,2024-01-10,30,Gold
4,105,Kiran,Mumbai,6500.0,<NA>,2024-01-15,28,Silver
5,106,Neha,Delhi,7000.0,7,2024-01-20,25,Silver
6,108,Riya,None,8000.0,8,2024-01-28,22,Platinum
7,110,Riya,Mumbai,7500.0,7,2024-02-05,22,Platinum

In [120]:
df.columns = df.columns.str.strip()

In [124]:
df2.columns = df2.columns.str.strip()

### 52- Perform left join.

In [141]:
left_join = pd.merge(df, df2, how = 'left', left_on = 'customer_name', right_on ='customer_name')
print(left_join)

   order_id customer_name     city   sales  quantity order_date   age  \
0       101          Amit    Delhi  5000.0       5.0 2024-01-01  30.0
1       102          Neha   Mumbai  7000.0       7.0 2024-01-05  25.0
2       103           Raj    Delhi  4000.0       4.0 2024-01-07  35.0
3       104          Amit  Chennai     NaN       6.0 2024-01-10  30.0
4       105         Kiran   Mumbai  6500.0       NaN 2024-01-15  28.0
5       106          Neha    Delhi  7000.0       7.0 2024-01-20  25.0
6       107          None  Chennai  3000.0       3.0 2024-01-25   NaN
7       108          Riya     None  8000.0       8.0 2024-01-28  22.0
8       109         Sahil    Delhi     NaN       2.0 2024-02-01   NaN
9       110          Riya   Mumbai  7500.0       7.0 2024-02-05  22.0

  membership
0       Gold
1     Silver
2       Gold
3       Gold
4     Silver
5     Silver
6        NaN
7   Platinum
8        NaN
9   Platinum

In [129]:
df.columns

Index(['order_id', 'customer_name', 'city', 'sales', 'quantity', 'order_date'], dtype='object')

In [130]:
df2.columns

Index(['customer_name', 'age', 'membership'], dtype='object')

In [133]:
df['customer_name']

0     Amit
1     Neha
2      Raj
3     Amit
4    Kiran
5     Neha
6     None
7     Riya
8    Sahil
9     Riya
Name: customer_name, dtype: object

In [136]:
for col in df.columns:
    print(repr(col))

'order_id'
'customer_name'
'city'
'sales'
'quantity'
'order_date'

### 53- Perform outer join.

In [140]:
outer_join = pd.merge(df, df2, how="outer", on="customer_name")
print(outer_join)

   order_id customer_name     city   sales  quantity order_date   age  \
0       101          Amit    Delhi  5000.0       5.0 2024-01-01  30.0
1       104          Amit  Chennai     NaN       6.0 2024-01-10  30.0
2       105         Kiran   Mumbai  6500.0       NaN 2024-01-15  28.0
3       102          Neha   Mumbai  7000.0       7.0 2024-01-05  25.0
4       106          Neha    Delhi  7000.0       7.0 2024-01-20  25.0
5       103           Raj    Delhi  4000.0       4.0 2024-01-07  35.0
6       108          Riya     None  8000.0       8.0 2024-01-28  22.0
7       110          Riya   Mumbai  7500.0       7.0 2024-02-05  22.0
8       109         Sahil    Delhi     NaN       2.0 2024-02-01   NaN
9       107          None  Chennai  3000.0       3.0 2024-01-25   NaN

  membership
0       Gold
1       Gold
2     Silver
3     Silver
4     Silver
5       Gold
6   Platinum
7   Platinum
8        NaN
9        NaN

### 54- Concatenate df and df2 vertically.

In [143]:
pd.concat([df, df2])

,order_id,customer_name,city,sales,quantity,order_date,age,membership
0,101.0,Amit,Delhi,5000.0,5.0,2024-01-01,NaN,NaN
1,102.0,Neha,Mumbai,7000.0,7.0,2024-01-05,NaN,NaN
2,103.0,Raj,Delhi,4000.0,4.0,2024-01-07,NaN,NaN
3,104.0,Amit,Chennai,NaN,6.0,2024-01-10,NaN,NaN
4,105.0,Kiran,Mumbai,6500.0,NaN,2024-01-15,NaN,NaN
5,106.0,Neha,Delhi,7000.0,7.0,2024-01-20,NaN,NaN
6,107.0,None,Chennai,3000.0,3.0,2024-01-25,NaN,NaN
7,108.0,Riya,None,8000.0,8.0,2024-01-28,NaN,NaN
8,109.0,Sahil,Delhi,NaN,2.0,2024-02-01,NaN,NaN
9,110.0,Riya,Mumbai,7500.0,7.0,2024-02-05,NaN,NaN
0,NaN,Amit,NaN,NaN,NaN,NaT,30.0,Gold
1,NaN,Neha,NaN,NaN,NaN,NaT,25.0,Silver
2,NaN,Raj,NaN,NaN,NaN,NaT,35.0,Gold
3,NaN,Kiran,NaN,NaN,NaN,NaT,28.0,Silver
4,NaN,Riya,NaN,NaN,NaN,NaT,22.0,Platinum

### 55- Concatenate horizontally.

In [144]:
pd.concat([df, df2], axis = 1)

,order_id,customer_name,city,sales,quantity,order_date,customer_name,age,membership
0,101,Amit,Delhi,5000.0,5.0,2024-01-01,Amit,30.0,Gold
1,102,Neha,Mumbai,7000.0,7.0,2024-01-05,Neha,25.0,Silver
2,103,Raj,Delhi,4000.0,4.0,2024-01-07,Raj,35.0,Gold
3,104,Amit,Chennai,NaN,6.0,2024-01-10,Kiran,28.0,Silver
4,105,Kiran,Mumbai,6500.0,NaN,2024-01-15,Riya,22.0,Platinum
5,106,Neha,Delhi,7000.0,7.0,2024-01-20,NaN,NaN,NaN
6,107,None,Chennai,3000.0,3.0,2024-01-25,NaN,NaN,NaN
7,108,Riya,None,8000.0,8.0,2024-01-28,NaN,NaN,NaN
8,109,Sahil,Delhi,NaN,2.0,2024-02-01,NaN,NaN,NaN
9,110,Riya,Mumbai,7500.0,7.0,2024-02-05,NaN,NaN,NaN

# Numpy

In [145]:
import numpy as np

### 🟢 NumPy Questions (56–65)

### 56-  Convert Pandas column to NumPy array (Convert sales column to a NumPy array.)

In [146]:
sales_array = df['sales'].to_numpy()
print(sales_array)

[5000. 7000. 4000.   nan 6500. 7000. 3000. 8000.   nan 7500.]

### 57 - Replace NaN values using NumPy

In [147]:
sales_array = np.nan_to_num(sales_array, nan = 0)
sales_array

array([5000., 7000., 4000.,    0., 6500., 7000., 3000., 8000.,    0.,
       7500.])

### 58-  Find mean, median, std using NumPy

In [150]:
#Mean of sales
mean_sales = np.mean('sales_array')
mean_sales

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None